spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test # DB 접속 URL
    username: sa # DB 접속 username
    password: # DB 접속 password, 없음
    driver-class-name: org.h2.Driver # DB 접속 드라이버
  h2.console:
    enabled: true # 콘솔 사용 여부, 로컬에서 웹 브라우저로도 접속 가능
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none